export const dashboardCards = [
  {
    title: "Payment Forms",
    url: "/insights/payments",
    value: 0,
    roles: ["budget-controller", "budget-owner"],
    adminRoles: ["dfpm", "ict-manager", "super-administrator", "es"],
    action: "view more",
    tag: "all",
  },
  {
    title: "Third Party Payments",
    url: "/insights/payments",
    value: 0,
    roles: ["budget-controller", "budget-owner"],
    adminRoles: ["dfpm", "ict-manager", "super-administrator", "es"],
    action: "view more",
    tag: "third-party-payment",
  },
  {
    title: "Staff Payments",
    url: "/insights/payments",
    value: 0,
    roles: ["budget-controller", "budget-owner"],
    adminRoles: ["dfpm", "ict-manager", "super-administrator", "es"],
    action: "view more",
    tag: "staff-payment",
  },
  {
    title: "Logistics Refunds",
    url: "/budget/logistics/refund/response",
    value: 0,
    roles: ["budget-controller", "budget-owner"],
    adminRoles: ["dfpm", "ict-manager", "super-administrator", "es"],
    action: "view more",
    tag: "refunds",
  },
  {
    title: "Reversal Requests",
    url: "/budget/reverse/payment",
    value: 0,
    roles: ["budget-controller", "budget-owner"],
    adminRoles: ["dfpm", "ict-manager", "super-administrator", "es"],
    action: "view more",
    tag: "reversals",
  },
  {
    title: "Pending Transactions",
    url: "/budget/payments",
    value: 0,
    roles: ["budget-controller", "budget-owner"],
    adminRoles: ["dfpm", "ict-manager", "super-administrator", "es"],
    action: "view more",
    tag: "pending",
  },
  {
    title: "Paid Transactions",
    url: "/budget/payments",
    value: 0,
    roles: ["budget-controller", "budget-owner"],
    adminRoles: ["dfpm", "ict-manager", "super-administrator", "es"],
    action: "view more",
    tag: "paid",
  },
  {
    title: "Reversed Transactions",
    url: "/budget/reverse/payment",
    value: 0,
    roles: ["budget-controller", "budget-owner"],
    adminRoles: ["dfpm", "ict-manager", "super-administrator", "es"],
    action: "view more",
    tag: "reversals",
  },
];
